day1/address_book/config/routes.rb
Rails.application.routes.draw do

  resources :contacts, only: [:index, :create, :show, :new, :edit, :update, :destroy]
  get ('/search') => 'contacts#search'
  get ('/favourites') => 'contacts#index_favourites'
  post ('/contacts/favourite/:id') => 'contacts#favourite'

end

day1/address_book/app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :address, presence: true
  validates :phone_number, format: { with: /[0-9]+\z/, message: "only allows numbers" }
  validates :email, format: { with: /([a-z\d_-]+)@([a-z\d_-]+)\.[a-z]{2,4}/, message: "please use a valid email" }
end

day1/address_book/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.order("name ASC")
  end

  def new
    @contact = Contact.new
  end

  def show
    @contact = Contact.find params[:id]
  end
  
  def edit
    @contact = Contact.find params[:id]
  end
  
  def destroy
    Contact.find(params[:id]).destroy
    redirect_to contacts_path, notice: 'Contact deleted'
  end
  
  def search
    @search = params[:search]
    @contacts_search = Contact.where("name LIKE ?", "#{@search}%")
  end
  
  def create
    @contact = Contact.new(contact_params)   
    if @contact.valid?
      @contact.save
      redirect_to :action => 'show', :id => @contact.id, notice: 'Contact was successfully created'
    else
      render :new
    end
  end
  
  def update
    @contact = Contact.find_by(id: params[:id])
    if @contact.update_attributes(contact_params)
      redirect_to contacts_path, notice: 'Contact was successfully updated.'
    else
      render :edit
    end
  end

  def index_favourites
    @favourites = Contact.where(favourite: true)
  end
  
  def favourite
    contact = Contact.find(params[:id])
    contact.update_attribute(:favourite, true)
    redirect_to contact_path(contact.id), notice: 'Marked as favourite!'
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :address, :phone_number, :email)
  end
end

day1/address_book/app/views/contacts/_form.html.erb
<%= form_for(contact) do |f| %>
	<%= render "layouts/errors", model: contact %>

	<div class="field">
		<p><%= f.label :name %></p>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<p><%= f.label :address %></p>
		<%= f.text_field :address %>
	</div>
	<div class="field">
		<p><%= f.label :phone_number %></p>
		<%= f.text_field :phone_number %>
	</div>
	<div class="field">
		<p><%= f.label :email %></p>
		<%= f.text_field :email %>
	</div>
	<div class="actions">
		<%= f.submit :class => 'submit' %>
	</div>	
<% end %>

day1/address_book/app/views/contacts/edit.html.erb
<h2>Edit contact</h2>

<%= render "form", contact: @contact %>

day1/address_book/app/views/contacts/index.html.erb
<h2>Contacts</h2>

<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:search, "Search contacts:") %>
  <%= text_field_tag(:search) %>
  <%= submit_tag("Search") %>
<% end %>

<% if @contacts.any? %>
<ul>
	<% @contacts.each do |contact| %>
	<li>
		<%= link_to contact.name, contact_path(contact) %>
	</li>
	<% end %>
</ul>
<% end %>

day1/address_book/app/views/contacts/index_favourites.html.erb
<h2>Favourite contacts</h2>

<% if @favourites.any? %>
<ul>
	<% @favourites.each do |contact| %>
	<li>
		<%= link_to contact.name, contact_path(contact) %>
	</li>
	<% end %>
</ul>
<% end %>

day1/address_book/app/views/contacts/new.html.erb
<h2>Add new contact</h2>

<%= render "form", contact: @contact %>

day1/address_book/app/views/contacts/search.html.erb
<h2><%= @contacts_search.count %> results for <%= @search %></h2>
<% if @contacts_search.any? %>
<ul>
	<% @contacts_search.each do |contact| %>
	<li>
		<%= link_to contact.name, contact_path(contact) %>
	</li>
	<% end %>
</ul>
<% else %>
<p>No <em><%= @search %></em> in your address book yet!</p>
<% end %>

<p><%= link_to 'Back to all contacts', '/contacts' %></p>

day1/address_book/app/views/contacts/show.html.erb
<h2><%= @contact.name %></h2>

<% if @contact.favourite == true %>
<h3 class="fav">Favourite</h3>
<% end %>

<p><%= @contact.address %></p>
<p><%= @contact.phone_number %></p>
<p><%= @contact.email %></p>

<%= link_to "Edit", edit_contact_path %>

<% if !@contact.favourite == true %>
	<%= form_tag "/contacts/favourite/" + @contact.id.to_s do %>
		<input class="submit" type="submit" value="Mark as favourite">
	<% end %>
<% end %>

<%= form_tag(contact_path(@contact), method:"delete") do %>
	<input class="submit warning" type="submit" value="Delete contact">
<% end %>

day1/address_book/app/views/layouts/_errors.html.erb
<% if model.errors.any? %>

<h2>
	<%= pluralize(model.errors.count, "error") %>
	<%= "prohibited this #{model.class.name} from being saved:" %>
</h2>

<ul>
	<% model.errors.full_messages.each do |message| %>
	<li>
		<%= message %>
	</li>
	<% end %>
</ul>

<% end %>

day1/address_book/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AddressBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav>
		<ul>
			<li><%= link_to 'All contacts', contacts_path %></li>
			<li><%= link_to "Favourite contacts", "/favourites" %>
</li>
			<li><%= link_to "Create new contact", new_contact_path %></li>
		</ul>
	</nav>
	<h1>Address Book</h1>

	<% flash.each do |key, value| %>
		<%= content_tag :div, value, class: "flash-info" %>
	<% end %>

	<%= yield %>

</body>
</html>