day4/concert_network/config/routes.rb
Rails.application.routes.draw do
  root 'concerts#index'

  get ("concerts/search") => "concerts#search_by_price"
  get ("concerts/popular") => "concerts#popular"

  get ("signup") => "users#new"
  post ("signup") => "users#create"
  get ("users/:name") => "users#show", as: "user"

  get ("login") => "sessions#new"
  post ("login") => "sessions#create"

  get ("logout") => "sessions#destroy"
  
  resources :concerts, only: [:index, :new, :create, :show] do
  	resources :comments, only: [:create]
  end

end

day4/concert_network/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :concert
end

day4/concert_network/app/models/concert.rb
class Concert < ActiveRecord::Base
	has_many :comments, dependent: :destroy

	has_attached_file :poster, styles: {:medium => "300x300>", :thumb => "100x100>"}
	validates_attachment_content_type :poster, :content_type => /\Aimage\/.*\Z/

	def self.sort_by_comments(number=10)
		self.all.sort { |x,y| y.comments.count <=> x.comments.count }[0..9]
	end
end

day4/concert_network/app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates :name, :email, presence: true, uniqueness: true

	after_initialize :set_default_role, :if => :new_record?

	def set_default_role
		unless self.role
			self.role = :user
		end
	end

end

day4/concert_network/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
  	if @current_user.nil?
  		@current_user = User.find_by_id(session[:user_id])
  	end
  	@current_user
  end

  def authorize_user
  	unless current_user
  		flash[:message] = "Log in please!"
  		redirect_to root_path
  	end
  end

  def admin_only
  	unless current_user && current_user.role == "admin"
  		flash[:message] = "Access denied, you must be an admin to access this page."
  		redirect_to root_path
  	end
  end
end

day4/concert_network/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		concert = Concert.find(params[:concert_id])
		comment = Comment.new text: params[:comment][:text].strip, concert_id: concert.id
		if comment.save
			redirect_to concert_path(concert)
		else
			render "concerts/show"
		end
	end
end

day4/concert_network/app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
	before_action :admin_only, only: [:create, :new]


	def index
		today = DateTime.current
		
		beginning_of_today = today.at_beginning_of_day
		end_of_today = today.at_end_of_day
		
		@today_concerts = Concert.where("date >= ? AND date < ?", beginning_of_today, end_of_today)
		@today_to_end_month_concerts = Concert.where("date > ? AND date <= ?", today, today.end_of_month.end_of_day)
	end

	def show
		@concert = Concert.find(params[:id])
		@comments = Comment.where(concert_id: @concert.id)
		@comment = Comment.new
	end

	def new
		@concert = Concert.new
	end

	def create
		concert = Concert.new concert_params
		if concert.save
			redirect_to concerts_path
		else
			render :new
		end
	end

	def search_by_price
		@amount = params[:amount]
		today = DateTime.current
		@concerts = Concert.where("price <= ? AND date >= ?", @amount, today)
	end

	def popular
		@concerts = Concert.sort_by_comments
	end

	private

	def concert_params
		params.require(:concert).permit(:band, :venue, :city, :date, :price, :description, :poster)
	end
end

day4/concert_network/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
			user = User.find_by_email(params[:email])
			if user && user.authenticate(params[:password])
				session[:user_id] = user.id
				redirect_to '/'	
			else
				redirect_to '/login'	
			end
	end

	def destroy
		session.clear
		redirect_to root_path	
	end	

end

day4/concert_network/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authorize_user, only: [:show]

	def new
		@user = User.new
	end

	def create
		user = User.new user_params
		if user.save
			name = user.name
			session[:user_id] = user.id
			redirect_to user_path(name)
		else
			render :new
		end
	end

	def show
		@user = User.find_by(session[:user_id])
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end
end

day4/concert_network/app/helpers/application_helper.rb
module ApplicationHelper
end

day4/concert_network/app/views/concerts/index.html.erb
<main class="col-md-8">
	<h2>Today</h2>
	<% if !@today_concerts.blank? %>
		<ul>
		<% @today_concerts.each do |concert| %>
			<li>
			<%= link_to "#{concert.band} - #{concert.city}", concert_path(concert) %>
			</li>
		<% end %>
		</ul>
	<% else %>
		<p>No concerts today :O</p>
	<% end %>
</main>

<aside class="col-md-4">
	<h2>Later this month</h2>

	<ul>
	<% @today_to_end_month_concerts.each do |concert| %>
		<li>
		<%= link_to "#{concert.band} - #{concert.city}", concert_path(concert) %>
		</li>
	<% end %>
	</ul>
</aside>

day4/concert_network/app/views/concerts/new.html.erb
<h2>Add a new concert</h2>

<%= form_for @concert do |f| %>
	<p><%= f.label :band %></p>
	<%= f.text_field :band %>
	<br />
	<p><%= f.label :venue %></p>
	<%= f.text_field :venue %>
	<br />
	<p><%= f.label :city %></p>
	<%= f.text_field :city %>
	<br />
	<p><%= f.label :date %></p>
	<%= f.date_field :date %>
	<br />
	<p><%= f.label :price %></p>
	<%= f.number_field :price %>
	<br />
	<p><%= f.label :description %></p>
	<%= f.text_area :description %>
	<br />
	<p><%= f.label :poster %></p>
	<%= f.file_field :poster %>
	<br />
	<%= f.submit %>
<% end %>

day4/concert_network/app/views/concerts/popular.html.erb
<h2>Most popular concerts</h2>

<% if !@concerts.blank? %>
	<ol>
	<% @concerts.each do |concert| %>
		<li><p>
		<%= link_to concert.band, concert_path(concert) %>
		 (<%= concert.city %>)  
		<%= concert.price %>€
		</p></li>
	<% end %>
	</ol>
<% end %>

day4/concert_network/app/views/concerts/search_by_price.html.erb
<h2>How much are you willing to spend?</h2>

<%= form_tag(concerts_search_path, method: "get") %>
<%= label_tag(:amount, "Maximum price") %>
<%= text_field_tag(:amount) %>
<%= submit_tag("Search concerts") %>

<% if !@concerts.blank? %>
	<h3><%= @concerts.count %> results for <%= @amount %>€ or less</h3>

	<ul>
	<% @concerts.each do |concert| %>
		<li><p>
		<%= link_to concert.band, concert_path(concert) %>
		 (<%= concert.city %>)  
		<%= concert.price %>€
		</p></li>
	<% end %>
	</ul>
<% end %>

day4/concert_network/app/views/concerts/show.html.erb
<h2>
<%= @concert.band %> <%= @concert.date.strftime("%d-%m-%Y") %> </h2>
<%= image_tag @concert.poster.url(:medium) %>
<p>City: <%= @concert.city %></p>
<p>Venue: <%= @concert.venue %></p>
<p>Time: <%= @concert.date.strftime("%H:%M") %></p>
<p>Price: <%= @concert.price %>€</p>
<p><%= @concert.description %></p>

<h3>Comments</h3>

<h4>What do you think?</h4>
<%= form_for [@concert, @comment] do |f| %>
	<%= f.text_area :text %>
	<br />
	<%= f.submit %>
<% end %>

<% if !@comments.blank? %>
	<h4><%= @comments.count %> <%= "comment".pluralize(@comments.count) %> so far</h4>

	<% @comments.each do |comment| %>
		<p><%= comment.text %></p>
		<p><%= comment.created_at.strftime("%d-%m-%Y at %H:%M") %></p>
	<% end %>
<% else %>
	<p>Be the first to comment!</p>
<% end %>

day4/concert_network/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConcertNetwork</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
	<nav class="navbar navbar-default">
		<ul class="nav navbar-nav">
			<li><%= link_to "Concerts", concerts_path %></li>
			<li><%= link_to "Add new concert", new_concert_path %></li>
			<li><%= link_to "Popular concerts", concerts_popular_path %></li>
			<li><%= link_to "Search by price", concerts_search_path %></li>
		</ul>
		<ul class="nav navbar-nav navbar-right">
			<% if current_user %>
				<li><%= link_to "Log out","/logout" %></li>
			<% else %>	
				<li><%= link_to "Log in", "/login" %></li>
				<li><%= link_to "Sign up", "/signup" %></li>
			<% end %>
		</ul>
	</nav>
	<h1>Find your next concert</h1>
</header>
<div class="container">

<% if flash[:message] %>
	<div class="alert alert-warning" role="alert"><%= flash[:message] %></div>
<% end %>

<%= yield %>
</div>
<footer class="footer">
  <div class="container">
		<small class="text-muted pull-left">© 2015</small>
		<p class="text-muted pull-right">Exercise for the web development bootcamp at <a href="http://www.ironhack.com">Ironhack</a></p>
  </div>
</footer>
</body>
</html>

day4/concert_network/app/views/users/new.html.erb
<%= form_for @user, url: "/signup" do |f| %>
	<p>Name: <%= f.text_field :name, class: "form-control" %></p>	
	<p>Email: <%= f.text_field :email, class: "form-control" %></p>
	<p>Password: <%= f.password_field :password, class: "form-control" %></p>
	<p>Password confirmation: <%= f.password_field :password_confirmation, class: "form-control" %></p>
	<%= f.submit "Submit" %>
<% end %>

day4/concert_network/app/views/users/show.html.erb
<b><p><%= @user.name %></p></b>
<p><%= @user.email %></p>