day3/auction_site/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :show, :new, :create, :destroy] do 
  	resources :products, only: [:index, :show, :new, :create, :destroy]
  end
  resources :products, only: [:index, :create, :new, :show] do
	  resources :bids, only: [:create]
  end
end

day3/auction_site/app/models/bid.rb
class Bid < ActiveRecord::Base
	belongs_to :product
	belongs_to :user

	validate :greater_than_min_bid
	validate :greater_than_current_max_bid
	validate :not_from_product_owner

	def greater_than_min_bid
		if amount <= product.min_bid
      errors.add(:amount, "can't be smaller than minimum bid")
    end
	end

	def greater_than_current_max_bid
		product = Product.find(product_id)
		current_max_bid = product.bids.max_by { |bid| bid.amount }
		current_max_bid_amount = current_max_bid.amount
		if amount <= current_max_bid_amount
			errors.add(:amount, "can't be smaller than current maximum bid")
		end
	end

	def not_from_product_owner
		owner_id = Product.find(product_id).user_id
		if user_id == owner_id
			errors.add(:email, "belongs to product owner, product owner can not bid")
		end
	end
end

day3/auction_site/app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :user
	has_many :bids

end

day3/auction_site/app/models/user.rb
class User < ActiveRecord::Base
	has_many :products
	has_many :bids

	validates :email, presence: true, uniqueness: true
end

day3/auction_site/app/controllers/bids_controller.rb
class BidsController < ApplicationController
	def create
		@product = Product.find(params[:product_id])
		# user_id = @product.user_id
		p params
		user = User.find_by_email(params[:email])
		@bid = user.bids.new amount: params[:amount], product_id: @product.id

		if @bid.valid? && @bid.present?
			@bid.save
			redirect_to product_path(@product)
		else
			@bids = Bid.where(product_id: @product.id) 
			if !@product.bids.blank? 
				highest_bid = @product.bids.max_by { |bid| bid.amount }
				@winner = User.find(highest_bid.user_id)
			end
			render "products/show"
		end
	end
end

day3/auction_site/app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all
	end

	def show
		@product = Product.find(params[:id])
		@bid = Bid.new
		@bids = Bid.where(product_id: @product.id) 
		# if !@product.bids.blank? 
		# 	highest_bid = @product.bids.max_by { |bid| bid.amount }
		# 	@winner = User.find(highest_bid.user_id)
		# end
	end

	def new
		@user = User.find(params[:user_id])
		@product = Product.new
	end

	def create
		@user = User.find(params[:user_id])
		@product = Product.new product_params

		if @product.valid? && @product.present?
			@product.user_id = params[:user_id]
			@product.save
			redirect_to user_path(@user), notice: "Product sucessfully added"
		else
			render :new
		end
	end

	def destroy

	end

	private

	def product_params
		params.require(:product).permit(:title, :description, :min_bid, :deadline)
	end
end

day3/auction_site/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new user_params

		if @user.valid? && @user.present?
			@user.save
			redirect_to user_path(@user), notice: "User #{@user.name} added correctly"
		else
			render :new
		end
	end

	def destroy

	end

	private

	def user_params
		params.require(:user).permit(:name, :email)
	end
end

day3/auction_site/app/views/layouts/_errors.html.erb
<% if model.errors.any? %>

<p><strong>
	<%= pluralize(model.errors.count, "error") %>
	<%= "prohibited this #{model.class.name} from being saved:" %>
</strong></p>

<ul>
	<% model.errors.full_messages.each do |message| %>
	<li>
		<%= message %>
	</li>
	<% end %>
</ul>

<% end %>

day3/auction_site/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuctionSite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
	<ul>
		<li><%= link_to 'Users', users_path %></li>
		<li><%= link_to 'New user', new_user_path %></li>
		<li><%= link_to 'Products', products_path %></li>
<!-- 		<li><%= link_to 'U', users_path %></li>
		<li><%= link_to 'Users', users_path %></li>
 -->	</ul>
</nav>

<h1>Auction site</h1>

<% flash.each do |key, value| %>
		<%= content_tag :div, value, class: "flash-info" %>
<% end %>

<%= yield %>

</body>
</html>

day3/auction_site/app/views/products/index.html.erb
<h2>Products available</h2>

<% if @products.blank? %>
	<p>No products yet</p>
<% else %>
	<% @products.each do |product| %>
		<ul>
			<li><%= link_to product.title, product_path(product) %></li>
		</ul>
	<% end %>
<% end %>

day3/auction_site/app/views/products/new.html.erb
<h2>Add new product</h2>

<%= form_for [@user, @product] do |f| %>
<%= render 'layouts/errors', model: @product %>

	<%= f.label :title %>
	<%= f.text_field :title %>
	<br />
	<%= f.label :description %>
	<%= f.text_field :description %>
	<br />
	<%= f.label :min_bid %>
	<%= f.number_field :min_bid %>
	<br />
	<%= f.label :deadline %>
	<%= f.date_field :deadline %>
	<br />
	<%= f.submit %>
<% end %>

day3/auction_site/app/views/products/show.html.erb
<h2><%= @product.title %></h2>

<p>Description: <%= @product.description %></p>
<p>Minimum bid: <%= @product.min_bid %>€</p>
<p>Bidding deadline: <%= @product.deadline %></p>

<% if @bids.blank? %>
	<p>No bids yet!</p>
<% else %>
	<h3>Bids for this product</h3>
	<% @bids.each do |bid| %>
		<ul>
			<li><strong><%= bid.user.name %>:</strong> <%= bid.amount %>€</li>
		</ul>
	<% end %>
<% end %>

<% if @product.deadline >= Date.current %>
	<h3>Do you want to bid?</h3>
	<%= form_tag product_bids_path(@product, @bid) do %>
	<%= render "layouts/errors", model: @bid %>
		<%= label_tag :amount %>
		<%= number_field_tag :amount %>
		<br />
		<%= label_tag :email %>
		<%= text_field_tag :email %>
		<br />
		<%= submit_tag 'Bid!' %>
	<% end %>
<% else %>
	<p><%= @winner.name %> won this bid</p>

<% end %>

day3/auction_site/app/views/users/index.html.erb
<h2>Users</h2>

<% if @users.blank? %>
	<p>No users yet</p>
<% else %>
	<% @users.each do |user| %>
		<ul>
			<li><%= link_to user.name, user_path(user) %></li>
		</ul>
	<% end %>
<% end %>

day3/auction_site/app/views/users/new.html.erb
<h2>Add new user</h2>

<%= form_for @user do |f| %>
<%= render 'layouts/errors', model: @user %>

	<%= f.label :name %>
	<%= f.text_field :name %>
	<br />
	<%= f.label :email %>
	<%= f.text_field :email %>
	<br />
	<%= f.submit %>
<% end %>

day3/auction_site/app/views/users/show.html.erb
<h2><%= @user.name %></h2>
<p>Email address: <%= @user.email %></p>
<p>Member since: <%= @user.created_at %></p>

<li><%= link_to 'New product', new_user_product_path(params[:id]) %></li>